name: Deploy Nginx and VuePress

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 根据 VuePress 要求设置 Node.js 版本

    - name: Install Dependencies
      run: npm install

    - name: Build VuePress
      run: npm run build

    - name: Setup SSH
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${DEPLOY_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 82.157.205.135 >> ~/.ssh/known_hosts

    - name: Deploy Files and Restart Services
      run: |
        ssh root@82.157.205.135 << EOF
          # 确保 nginx 配置和 VuePress 构建目录已存在
          mkdir -p /home/thought/etc/nginx/conf.d
          mkdir -p /home/thought/vuepress

          # 上传最新的 Nginx 配置和 VuePress 构建目录
          rsync -avz ./nginx-conf/ /home/thought/etc/nginx/conf.d/
          rsync -avz ./docs/.vuepress/dist/ /home/thought/vuepress/

          # 启动或重启 Docker 服务
          cd /home/thought/etc/
          docker-compose down
          docker-compose up -d
        EOF
